---
title: "Parameterized Reports"
output:
  html_document:
    toc: true
    toc_depth: 3
---

## Overview

R Markdown documents can optionally include one or more parameters. Parameters are useful when you want to re-render the same report with distinct values for various key inputs, for example:

1. Running a report specific to a department or geographic region.

2. Running a report that covers a specific period in time.

3. Running multiple versions of a report for distinct sets of core assumptions.

R Markdown parameter names, types, and default values are declared in the YAML section at the top of the document. To change these values for a given rendering you use the `params` argument to the `rmarkdown::render` function.

Note that parameterized reports are a new feature of R Markdown and therefore require very recent versions of the **knitr** (v1.10.5) and **rmarkdown** (v0.7) packages. You can install the most up to date versions with the following command:

```r
install.packages(c("knitr", "rmarkdown"))
```

If you are using RStudio you should also download the [most recent version](http://www.rstudio.com/products/rstudio/download/) of RStudio v0.99 (as it has some additional changes required to support parameterized reports).

## Declararing Parameters

Parameters are declared using the `params` field within the YAML section at the top of the document, for example:

```yaml
---
title: My Document
output: html_document
params:
   region: east
---
```

Parameter values can be provided inline as illustrated above or can be included in a value sub-key. For example:

```yaml
---
title: My Document
output: html_document
params:
  region:
    value: east
---
```

This second form is useful when you need to provide additional details about the parameter (e.g. information about how parameters should be presented to end-users). 

## Accessing Parameters from R

The declared parameters are automatically made available within the knit environment as components of a read-only list named `params`. For example, the values of the above two parameters can be accessed with the following R code:

```r
params$region
params$start
```

When you preview the document in RStudio (or otherwise call the `rmarkdown::render` function with no arguments) the default parameter values listed in the YAML will be used.


## Passing Parameters

To vary the parameters of an R Markdown document from the defaults you use the `params` argument of the `rmarkdown::render` function. For example:

```r
rmarkdown::render("MyDocument.Rmd", params = list(
  region = "west",
  start = as.Date("2015-02-01")
))
```

You can of course specify only a subset of the available parameters in your call to render. For example:

```r
rmarkdown::render("MyDocument.Rmd", params = list(
  region = "west"
))
```

In this case the default values are used for any parameters not explicitly provided.


You might also find it convenient to wrap the call to render in an R function, for example:

```r
renderMyDocument <- function(region, start) {
  rmarkdown::render("MyDocument.Rmd", params = list(
    region = region,
    start = start
  ))
}
```

## Parameter Types

All of the standard R types that can be parsed by the `yaml::yaml.load` function are supported including `character`, `integer`, `numeric`, and `logical`. In addition, you can use arbitrary other R object types by specifying the value using an R expression. For example, to specify a date, date-time, or data frame you could use this code:

```yaml
---
title: My Document
output: html_document
params:
  start: !r as.Date("2015-01-01")
  snapshot: !r as.POSIXct("2015-01-01 12:30:00")
  data: !r datasets::mtcars
---
```

The key is to preface the value with `!r`, which indicates that the value is an R expression rather than a literal value.

## Specifying Empty Values

Sometimes the default value for a parameter is more naturally expressed as empty or missing. For example, a `maxrows` parameter might be available but when not specified results in all rows being utilized.

The most obvious and natural way to specify an empty value is with `null`. However, this won't work without some additional context because the underlying R object type of all parameters must be discoverable using only what is contained in the `params` declaration (this is so that front-ends can present an appropriate user-interface for customizing parameters). 

There are several syntactic options for specifying empty values. First, you can explicitly designate the R object class via the `class` field:

```yaml
---
title: My Document
output: html_document
params:
  maxrows: 
     value: null
     class: integer
---
```

Second, you can provide a sentinel value that is understood to mean empty (for example, -1 for an integer or "" for a character):

```yaml
---
title: My Document
output: html_document
params:
  maxrows: -1
---
```

You'd then check for this sentinel value directly in your R code (e.g. `if (params$maxrows != -1) {}`. Another very similar technique is to use a zero-length vector as the sentinel empty value then use the `length` function to check whether it was specified. For example:

```yaml
---
title: My Document
output: html_document
params:
  maxrows: integer()
---
```

The code `if(length(params$maxrows)) {}` could then be used to test whether a value was provided for the `maxrows` parameter.


