---
title: "R Markdown &mdash; Dynamic Documents for R"
---

## Overview

R Markdown is an authoring format that enables easy authoring of dynamic documents from R. It combines the core syntax of markdown (an easy-to-write plain text format) with embedded R code chunks that are run so their output can be included in the final document.

With R Markdown you can author a single source file that can be used to generate output in many formats including HTML, PDF, and MS Word. R Markdown isn't limited to just plain documents either, extensive support for HTML5 and PDF (Beamer) presentations is also included.

Under the hood R Markdown is implemented using the [knitr](http://yihui.name/knitr/) package (for executing embedded R code chunks) and [pandoc](http://johnmacfarlane.net/pandoc/) (for converting to various output formats). The [R Markdown v2 Specification](rmarkdown_v2.html) includes a detailed review of supported features and syntax.

#### Using R Markdown

You can use R Markdown either through the **rmarkdown** package or via the integrated support for R Markdown within RStudio:

1. To use R Markdown within RStudio you should download the current [RStudio Preview Release](http://www.rstudio.com/ide/download/preview).

2. To use R Markdown in other envrionments you should install the [rmarkdown package](https://github.com/rstudio/rmarkdown) from GitHub.

## Quick Tour





