---
title: "Introduction"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [include_header.html, include_lessons_nav.html]
      after_body: [include_lessons_nav_end.html, include_footer.html]
---

### Overview

R Markdown provides an authoring framework for data science. You can use a single R Markdown file to both 

* save and execute code
* generate high quality reports that can be shared with an audience 

R Markdown documents are fully reproducible and support dozens of static and dynamic output formats. This 1-minute video provides a quick tour of what's possible with R Markdown:


<iframe src="https://player.vimeo.com/video/178485416" width="700" height="394" frameborder="0" style="margin-bottom: 2em;" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

### Installation

Like the rest of R, R Markdown is free and open source. You can install the R Markdown package from CRAN with:

```r
install.packages("rmarkdown")
```

### Get Started

The links to the left provide a quick tour of R Markdown. The links at the top provide examples of R Markdown documents, as well as an in depth discussion of various R Markdown topics. 

You may also find the following resources helpful:

* [The R Markdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
* [The R Markdown Reference Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

***
## [Continue to How It Works](lesson-2.html){.continue-link}
