blank_issues_enabled: false
contact_links:
  - name: Issue guide
    url: https://yihui.org/issue/
    about: First time here or need a refresh? Please consult the issue guide before posting.
  - name: Ask a question on Posit Forum
    url: https://forum.posit.co/
    about: Please ask and answer questions here.
  - name: Ask a question on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/r+r-markdown
    about: Please ask and answer questions here.
