
#' @export
render <- function(input,
                   output_format = NULL,
                   output_file = NULL,
                   output_options = NULL,
                   clean = TRUE,
                   params = NULL,
                   envir = parent.frame(),
                   quiet = FALSE,
                   encoding = getOption("encoding")) {

  # check for "all" output formats
  if (identical(output_format, "all")) {
    output_format <- enumerate_output_formats(input, envir, encoding)
    if (is.null(output_format))
      output_format <- "html_document"
  }

  # check for a list of output formats -- if there is more than one
  # then recursively call this function with each format by name
  if (is.character(output_format) && length(output_format) > 1) {
    outputs <- character()
    for (format in output_format) {
      output <- render(input, format, NULL, output_options,
                       clean, params, envir, quiet, encoding)
      outputs <- c(outputs, output)
    }
    return(invisible(outputs))
  }

  # check for required version of pandoc
  required_pandoc <- "1.12.3"
  if (!pandoc_available(required_pandoc)) {
    stop("pandoc version ", required_pandoc, " or higher ",
         "is required and was not found.", call. = FALSE)
  }

  # setup a cleanup function for intermediate files
  intermediates <- c()
  on.exit(lapply(intermediates,
                 function(f) {
                   if (clean && file.exists(f))
                     unlink(f, recursive = TRUE)
                 }),
          add = TRUE)

  # if the input file has spaces in it's name then make a copy
  # that doesn't have spaces
  if (grepl(' ', basename(input), fixed=TRUE)) {
    input_no_spaces <- file_name_without_spaces(input)
    if (file.exists(input_no_spaces)) {
      stop("The name of the input file cannot contain spaces (attempted to ",
           "copy to a version without spaces '", input_no_spaces, "' ",
           "however that file already exists)", call. = FALSE)
    }
    file.copy(input, input_no_spaces, overwrite = TRUE)
    intermediates <- c(intermediates, input_no_spaces)
    input <- input_no_spaces
  }

  # execute within the input file's directory
  oldwd <- setwd(dirname(tools::file_path_as_absolute(input)))
  on.exit(setwd(oldwd), add = TRUE)

  # reset the name of the input file to be relative and calculate variations
  # on the filename for our various intermediate targets
  input <- basename(input)
  knit_input <- input
  knit_output <- file_with_meta_ext(input, "knit", "md")
  intermediates <- c(intermediates, knit_output)
  utf8_input <- file_with_meta_ext(input, "utf8", "md")
  intermediates <- c(intermediates, utf8_input)

  # if this is an R script then spin it first
  if (identical(tolower(tools::file_ext(input)), "r")) {
    # make a copy of the file to spin
    spin_input <- file_with_meta_ext(input, "spin", "R")
    file.copy(input, spin_input, overwrite = TRUE)
    intermediates <- c(intermediates, spin_input)
    # spin it
    spin_rmd <- knitr::spin(spin_input,
                            knit = FALSE,
                            envir = envir,
                            format = "Rmd")
    intermediates <- c(intermediates, spin_rmd)
    knit_input <- spin_rmd
    # append default metadata (this will be ignored if there is user
    # metadata elsewhere in the file)
    metadata <- paste('\n',
      '---\n',
      'title: "', input, '"\n',
      'author: "', Sys.info()[["user"]], '"\n',
      'date: "', date(), '"\n',
      '---\n'
    , sep = "")
    if (!identical(encoding, "native.enc"))
      metadata <- iconv(metadata, to = encoding)
    cat(metadata, file = knit_input, append = TRUE)
  }

  # read the input file
  input_lines <- read_lines_utf8(knit_input, encoding)

  # if we haven't been passed a fully formed output format then
  # resolve it by looking at the yaml
  if (!is_output_format(output_format)) {
    output_format <- output_format_from_yaml_front_matter(input_lines,
                                                          output_options,
                                                          output_format)
    output_format <- create_output_format(output_format$name,
                                          output_format$options)
  }

  # automatically create an output file name if necessary
  if (is.null(output_file))
    output_file <- pandoc_output_file(input, output_format$pandoc$to)

  # use output filename based files dir
  files_dir <- knitr_files_dir(basename(output_file))

  # default to no knit_meta (some may be generated by the knit)
  knit_meta <- NULL

  # knit if necessary
  if (tolower(tools::file_ext(input)) %in% c("r", "rmd", "rmarkdown")) {

    # restore options and hooks after knit
    optk <- knitr::opts_knit$get()
    on.exit(knitr::opts_knit$restore(optk), add = TRUE)
    optc <- knitr::opts_chunk$get()
    on.exit(knitr::opts_chunk$restore(optc), add = TRUE)
    hooks <- knitr::knit_hooks$get()
    on.exit(knitr::knit_hooks$restore(hooks), add = TRUE)

    # reset knit_meta (and ensure it's always reset before exiting render)
    knit_meta_reset()
    on.exit(knit_meta_reset(), add = TRUE)

    # default rendering and chunk options
    knitr::render_markdown()
    knitr::opts_chunk$set(tidy = FALSE, error = FALSE)

    # enable knitr hooks to have knowledge of the final output format
    knitr::opts_knit$set(rmarkdown.pandoc.to = output_format$pandoc$to)
    knitr::opts_knit$set(rmarkdown.version = 2)

    # trim whitespace from around source code
    if (packageVersion("knitr") < "1.5.23") {
      local({
        hook_source = knitr::knit_hooks$get('source')
        knitr::knit_hooks$set(source = function(x, options) {
          hook_source(strip_white(x), options)
        })
      })
    }

    # use filename based figure and cache directories
    figures_dir <- paste(files_dir,
                         "/figure-", output_format$pandoc$to, "/",
                         sep = "")
    knitr::opts_chunk$set(fig.path=figures_dir)
    cache_dir <- knitr_cache_dir(input)
    knitr::opts_chunk$set(cache.path=paste(cache_dir, "/", sep=""))

    # merge user options and hooks
    if (!is.null(output_format$knitr)) {
      knitr::opts_knit$set(as.list(output_format$knitr$opts_knit))
      knitr::opts_chunk$set(as.list(output_format$knitr$opts_chunk))
      knitr::knit_hooks$set(as.list(output_format$knitr$knit_hooks))
    }

    # if there isn't already an entity named "params" in the knit
    # environment then merge any params passed to this function into the
    # yaml front matter and make that available in the knit environment
    # as "params" (then remove the value from the environment on exit)
    if (!exists("params", envir = envir)) {
      yaml_front_matter <- parse_yaml_front_matter(input_lines)
      params <- merge_lists(yaml_front_matter, params)
      assign("params", params, envir = envir)
      on.exit(remove("params", envir = envir), add = TRUE)
    } else {
      warning("'params' value already exists in knit environment, not ",
              "adding YAML params")
    }

    # perform the knit
    input <- knitr::knit(knit_input,
                         knit_output,
                         envir = envir,
                         quiet = quiet,
                         encoding = encoding)

    # collect knit_meta
    knit_meta <- knit_meta_reset()

    # clean the files_dir if we've either been asking to clean supporting
    # files or if we know the supporting files are going to get copied
    # to an output directory. however, don't ever clean the files_dir if
    # the knitr cache is active
    if (output_format$clean_supporting ||
        (dirname(input) != dirname(output_file))) {
        if (!file.exists(cache_dir))
          intermediates <- c(intermediates, files_dir)
    }
  }

  # read the input text as UTF-8 then write it back out
  input_text <- read_lines_utf8(input, encoding)
  writeLines(input_text, utf8_input, useBytes = TRUE)

  # call any pre_processor
  if (!is.null(output_format$pre_processor)) {
    extra_args <- output_format$pre_processor(input_text, knit_meta, files_dir)
    output_format$pandoc$args <- c(output_format$pandoc$args, extra_args)
  }

  # copy supporting files to the output directory if necessary
  if (!output_format$clean_supporting) {
    if (dirname(input) != dirname(output_file)) {
      file.copy(from = files_dir,
                to = dirname(output_file),
                recursive = TRUE)
    }
  }

  # run intermediate conversion if it's been specified
  if (output_format$pandoc$keep_tex) {
    pandoc_convert(utf8_input,
                   output_format$pandoc$to,
                   output_format$pandoc$from,
                   file_with_ext(output_file, "tex"),
                   TRUE,
                   output_format$pandoc$args,
                   !quiet)
  }

  # run the main conversion
  pandoc_convert(utf8_input,
                 output_format$pandoc$to,
                 output_format$pandoc$from,
                 output_file,
                 TRUE,
                 output_format$pandoc$args,
                 !quiet)

  # if there is a post-processor then call it
  if (!is.null(output_format$post_processor))
    output_format$post_processor(utf8_input, output_file, !quiet)

  if (!quiet)
    message("\nOutput created: ", output_file)

  # return the full path to the output file
  invisible(tools::file_path_as_absolute(output_file))
}


#' Render supporting files for an input document
#'
#' Render (copy) required supporting files for an input document to the _files
#' directory associated with the document.
#'
#' @param from Directory to copy from
#' @param files_dir Directory to copy files into
#' @param rename_to Optional rename of source directory after it is copied
#'
#' @return The relative path to the supporting files. This path is suitable
#' for inclusion in HTML\code{href} and \code{src} attributes.
#'
#' @export
render_supporting_files <- function(from, files_dir, rename_to = NULL) {

  # auto-create directory for supporting files
  if (!file.exists(files_dir))
    dir.create(files_dir)

  # target directory is based on the dirname of the path or the rename_to
  # value if it was provided
  target_stage_dir <- file.path(files_dir, basename(from))
  target_dir <- file.path(files_dir, ifelse(is.null(rename_to),
                                     basename(from),
                                     rename_to))

  # copy the directory if it hasn't already been copied
  if (!file.exists(target_dir) && !file.exists(target_stage_dir)) {
    file.copy(from = from,
              to = files_dir,
              recursive = TRUE)
    if (!is.null(rename_to)) {
      file.rename(from = target_stage_dir,
                  to = target_dir)
    }
  }

  # return the target dir (used to form links in the HTML)
  target_dir
}

# reset knitr meta output (returns any meta output generated since the last
# call to knit_meta_reset)
knit_meta_reset <- function() {
  if (packageVersion("knitr") >= "1.5.25")
    knitr::knit_meta(clean = TRUE)
  else
    NULL
}



