---
title: "Interactive components"
output: flexdashboard::flex_dashboard
runtime: shiny    
---

```{r include = FALSE}
library(flexdashboard)
```


# Introduction {.sidebar}

Move the sliders to make each pair of value boxes and gauges respond.
  
# Dashboard

## Slider column

### Slider Value {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = input$slider,
    icon = "fa-area-chart",
    color = if (input$slider >= 5) "warning" else "primary"
  )
})
```


### Slider Value 

```{r}
renderGauge({
  gauge(input$slider, min = 0, max = 10, gaugeSectors(
    success = c(0, 4), 
    warning = c(4, 7), 
    danger = c(7, 10)
  ))
})
```

### Slider

```{r echo=FALSE}
sliderInput("slider", "Choose a number",
            min = 0, max = 10, value = 1, step = 1)
```

## Numeric Input column

### Numeric Input Value {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = input$num,
    icon = "fa-area-chart",
    color = if (input$num >= 5) "warning" else "primary"
  )
})
```


### Numeric Input Value 

```{r}
renderGauge({
  gauge(input$num, min = 0, max = 10, gaugeSectors(
    success = c(0, 4), 
    warning = c(4, 7), 
    danger = c(7, 10)
  ))
})
```

### Numeric Input

```{r echo=FALSE}
# Maximum number of raw data rows to keep
numericInput("num", "Choose a number", 1, min = 0, max = 10 )
```
